version: '3.4'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'

  api:
    build: ./api
    command: sh -c 'sleep 10; ./api/node_modules/.bin/nodemon --inspect=0.0.0.0:9229 --legacy-watch api/index.js'
    environment:
      - PORT=3030
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DBHOST=mongodb
      - DBNAME=patents
    ports:
      - '3030:3030'
      - '9229:9229'
      - '9230:9230'
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/api

  web:
    build:
      context: ./web
      target: 'develop-stage'
    command: /bin/sh -c "npm run serve"
    environment:
      - VUE_APP_API_URL=http://localhost:3030
    ports:
    - '8080:8080'
    volumes:
      - ./web:/usr/src/web
      - mock:/usr/src/web/node_modules

volumes:
  mock: